INSERT INTO t_p80947900_training_platform_ma.users (user_id, department_id, full_name, login, password_hash, role) VALUES
(1,  1, 'Коткина Татьяна Васильевна',        'kotkina.t',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'admin'),
(2,  2, 'Петрова Светлана Игоревна',          'petrova.s',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(3,  3, 'Шуйгина Татьяна Павловна',           'shujgina.t',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(4,  3, 'Смирнов Андрей Викторович',          'smirnov.a',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(5,  3, 'Кузнецов Максим Сергеевич',          'kuznecov.m',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(6,  3, 'Пытащова Людмила Васильевна',        'pytashova.l',  '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(7,  3, 'Морозов Артем Алексеевич',           'morozov.a',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(8,  3, 'Иванов Станислав Юрьевич',           'ivanov.s',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(9,  3, 'Коткин Алексей Витальевич',          'kotkin.a',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(10, 3, 'Бурмагина Елена Алексеевна',         'burmagina.e',  '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(11, 3, 'Дементьева Мария Алексеевна',        'dementeva.m',  '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(12, 3, 'Калитина Мария Александровна',       'kalitina.m',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(13, 3, 'Фомина Дарья Петровна',              'fomina.d',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(14, 3, 'Ушакова Анна Олеговна',              'ushakova.a',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(15, 3, 'Михайлов Леонид Петрович',           'mihajlov.l',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(16, 3, 'Попова Мария Алексеевна',            'popova.m',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(17, 4, 'Золин Виктор Геннадьевич',           'zolin.v',      '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'admin'),
(18, 5, 'Новикова Елена Дмитриевна',          'novikova.e',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(19, 5, 'Калитин Василий Павлович',           'kalitin.v',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(20, 5, 'Патокин Павел Валерьевич',           'patokin.p',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(21, 6, 'Шишкина Дарья Васильевна',           'shishkina.d',  '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(22, 6, 'Пивоварова Наталья Владимировна',    'pivovarova.n', '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(23, 6, 'Злобин Владимир Павлович',           'zlobin.v',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(24, 6, 'Попов Павел Юрьевич',                'popov.p',      '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(25, 6, 'Кузнецов Марина Александровна',      'kuznecov.ma',  '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(26, 7, 'Васильев Олег Николаевич',           'vasilev.o',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(27, 7, 'Павлов Сергей Петрович',             'pavlov.s',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(28, 7, 'Волков Дмитрий Юрьевич',            'volkov.d',     '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(29, 7, 'Семенов Илья Игоревич',              'semenov.i',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(30, 7, 'Михайлов Виктор Степанович',         'mihajlov.v',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(31, 7, 'Сметанин Андрей Владимирович',       'smetanin.a',   '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker'),
(32, 8, 'Сидоров Игорь Владимирович',         'sidorov.i',    '$2b$12$KIx5RkBYv6GkFQ9z1mN8/.Y7LPzQRBBvbQwT7Ht4pRJnKgVJhKrSy', 'worker');

SELECT setval('t_p80947900_training_platform_ma.users_user_id_seq', 32);
